version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: microservices
    depends_on:
      - mysqldb
    command: ["./wait-for-it.sh", "mysqldb:3306", "--", "java", "-jar", "quiz-0.0.1-SNAPSHOT.jar"]



  mysqldb:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: microservices
      MYSQL_ROOT_PASSWORD: root
